services:
  - type: web
    name: ytmusicapi-cloud
    runtime: python
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: CORS_ORIGINS
        value: "*"
